version: '2'
services:
  wemall:
    image: wemall:1.0
    container_name: wemall
    hostname: wemall
    command: /usr/sbin/sshd -D
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
    - "80:80"
    - "443:443"
    - "8010:8010"
    - "8011:8011"
    - "8012:8012"
    extra_hosts:
     - "dev.wemall.com:127.0.0.1"